login:
  path: /login
  controller: App\Controller\SecurityController::loginAction

register:
  path: /register
  controller: App\Controller\RegistrationController::registerAction

home:
  path: /home
  controller: App\Controller\HomeController::homeAction

postComment:
  path: /postComment
  controller: App\Controller\AddCommentController::commentAction

postPost:
  path: /postPost/{id}
  controller: App\Controller\AddPostController::postAction

showPost:
  path: /showPost/{id}
  controller: App\Controller\AddPostController::showPost

deletePost:
    path: /deletePost/{id}
    controller: App\Controller\AddPostController::deletePost